# Generated by Django 4.2.2 on 2023-07-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'manufacturer_name': 'manu'}, on_delete=django.db.models.deletion.DO_NOTHING, to='relations.manufacturer'),
        ),
    ]
