# Generated by Django 4.2.2 on 2023-07-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'manufacturer_name': 'manu1'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='relations.manufacturer'),
        ),
    ]
