# Generated by Django 4.2.2 on 2023-07-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0008_partnership_manufacturer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relations.manufacturer')),
            ],
        ),
    ]
