# Generated by Django 4.2.2 on 2023-07-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0009_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='foreign_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key', to='relations.manufacturer'),
        ),
    ]
