# Generated by Django 4.2.2 on 2023-07-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0010_bike_foreign_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='manufacturer',
            new_name='one_to_one',
        ),
    ]
