# Generated by Django 4.2.2 on 2023-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0011_rename_manufacturer_bike_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='many_to_many',
            field=models.ManyToManyField(related_name='many_to_many', to='relations.manufacturer'),
        ),
    ]
