# Generated by Django 4.2.2 on 2023-07-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0013_alter_bike_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='one_to_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='relations.manufacturer'),
        ),
    ]
