# Generated by Django 4.2.2 on 2023-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0017_aadhar_vehicle_person_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
