# Generated by Django 4.2.2 on 2023-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_vehicle_choice_alter_student_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vehicle_choice',
            field=models.CharField(choices=[('C', 'Car'), ('T', 'Truck'), ('J', 'Jet Ski')], default='T', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], db_comment='Date and time when the article was published', max_length=8),
        ),
    ]
