# Generated by Django 4.2.2 on 2023-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_student_vehicle_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='big_integer_field',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], db_comment='Date and time when the article was published', db_index=True, db_tablespace='test_it', help_text='just for testing help_text', max_length=8, verbose_name='test year school'),
        ),
    ]
