# Generated by Django 4.2.2 on 2023-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_student_big_integer_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='big_integer_field',
            field=models.BigIntegerField(default=12),
        ),
    ]
