# Generated by Django 4.2.2 on 2023-07-10 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('reporter', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('today_date', models.DateField(default=datetime.date(2023, 7, 10))),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('time_field', models.TimeField(auto_now_add=True, null=True)),
                ('time_field_auto_f', models.TimeField(auto_now=True, null=True)),
                ('now', models.DateField(default=datetime.date(2023, 7, 10))),
            ],
        ),
    ]
