# Generated by Django 4.2.2 on 2023-07-11 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='today_date',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
        migrations.AlterField(
            model_name='question',
            name='now',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
    ]
