# Generated by Django 4.2.2 on 2023-07-12 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_code', '0002_alter_article_today_date_alter_question_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='today_date',
            field=models.DateField(default=datetime.date(2023, 7, 12)),
        ),
        migrations.AlterField(
            model_name='question',
            name='now',
            field=models.DateField(default=datetime.date(2023, 7, 12)),
        ),
    ]
