# Generated by Django 4.2.2 on 2023-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_field',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_field_auto_f',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
